/* Reaction Tree data — all 160 reactions from the OChem reference,
   organized by SUBSTRATE class. Each tree has branches (one per reaction)
   with text-based products + 3 distractors for multiple choice.

   Branch fields:
     id            — unique within tree (used for state)
     rxnId         — matches the canonical reference list (1..160)
     reagent       — short top-line reagent (renders on the branch arrow)
     conditions    — second line (catalyst / solvent / temperature)
     productName   — short label of the correct product (the leaf)
     productLong   — sentence-form description shown on reveal
     distractors   — 3 wrong product names (multiple choice)
     mechanism     — mechanism class (also serves as quick-explain header)
     explain       — 1–3 sentence mechanism summary
*/

/* ── Helpers ─────────────────────────────────────────────── */
const _D = {
  // Reusable distractor pools so I can write trees compactly.
  // (Each branch still picks 3 specific entries.)
  alkane: 'Alkane (no functional group)',
  alkene: 'Alkene',
  diol_vic: 'Vicinal diol',
  diol_gem: 'Geminal diol (hydrate)',
  diene: 'Conjugated diene',
  arene: 'Arene (aromatic ring)',
  alc1: 'Primary alcohol',
  alc2: 'Secondary alcohol',
  alc3: 'Tertiary alcohol',
  ald: 'Aldehyde',
  ket: 'Ketone',
  acid: 'Carboxylic acid',
  ester: 'Ester',
  amide: 'Amide',
  amine1: 'Primary amine',
  amine2: 'Secondary amine',
  amine3: 'Tertiary amine',
  nitrile: 'Nitrile',
  epoxide: 'Epoxide',
  ether: 'Ether',
  rx: 'Alkyl halide',
  rxgem: 'Geminal dihalide',
  rxvic: 'Vicinal dihalide',
  rh1: 'Vinyl halide',
  cyclopropane: 'Cyclopropane derivative',
  imine: 'Imine (Schiff base)',
  enamine: 'Enamine',
  acetal: 'Acetal',
  cyanohydrin: 'Cyanohydrin (α-hydroxy nitrile)',
  hydrazone: 'Hydrazone',
  oxime: 'Oxime',
  lactam: 'Lactam (cyclic amide)',
  lactone: 'Lactone (cyclic ester)',
  starting: 'Starting material returned unreacted',
};

/* ── Tree definitions ────────────────────────────────────── */
const TREES = {

  /* ═══════════ 1. ALKENE ═══════════ */
  alkene: {
    id: 'alkene',
    label: 'Alkene',
    subtitle: 'C=C',
    trunkMolecule: 'propene',
    blurb: 'Electron-rich π bond, attacked by electrophiles. The most-substituted carbon usually wins (Markovnikov), but special reagents override that.',
    branches: [
      { id:'a01', rxnId:1, reagent:'HX', conditions:'HCl, HBr or HI',
        productName:'Alkyl halide (Markovnikov)', productLong:'X adds to the more substituted carbon via the more stable carbocation.',
        distractors:['Alkyl halide (anti-Markovnikov)', _D.diol_vic, _D.alkane],
        mechanism:'Electrophilic Addition', explain:'H⁺ protonates the π bond to form the more stable cation. X⁻ then captures the cation, putting X on the more substituted carbon.' },
      { id:'a02', rxnId:2, reagent:'HBr', conditions:'ROOR or hν',
        productName:'Alkyl bromide (anti-Markovnikov)', productLong:'Peroxide initiation flips selectivity: Br ends up on the less substituted carbon.',
        distractors:['Alkyl bromide (Markovnikov)', 'Vicinal dibromide', _D.alc1],
        mechanism:'Radical Addition', explain:'Peroxide generates Br•, which adds to give the more stable C radical (at the more substituted C). Then H–Br donates H to the radical — Br ends up on the less substituted carbon.' },
      { id:'a03', rxnId:3, reagent:'X₂', conditions:'CCl₄ (inert)',
        productName:'Vicinal dihalide', productLong:'Two halogens add anti across the π bond via a bridged halonium.',
        distractors:[_D.rxgem, _D.diol_vic, 'Halohydrin'],
        mechanism:'Electrophilic Addition', explain:'X₂ forms a 3-membered halonium ion. The other X⁻ opens it from the opposite face → trans, anti-addition.' },
      { id:'a04', rxnId:4, reagent:'X₂', conditions:'H₂O',
        productName:'Halohydrin', productLong:'X and OH on adjacent carbons, anti; OH on more substituted C.',
        distractors:[_D.rxvic, _D.diol_vic, _D.epoxide],
        mechanism:'Electrophilic Addition', explain:'A halonium forms, then water (not X⁻) attacks the more substituted carbon of the halonium, where positive character is greatest. Anti, Markovnikov OH.' },
      { id:'a05', rxnId:5, reagent:'H₂O', conditions:'H₂SO₄ (cat.)',
        productName:'Alcohol (Markovnikov)', productLong:'Acid-catalyzed hydration — OH on the more substituted carbon.',
        distractors:['Alcohol (anti-Markovnikov)', _D.ether, _D.diol_vic],
        mechanism:'Electrophilic Addition', explain:'H⁺ protonates the alkene to form the more stable cation. Water attacks, then loses a proton to give the alcohol.' },
      { id:'a06', rxnId:6, reagent:'1) Hg(OAc)₂, H₂O', conditions:'2) NaBH₄',
        productName:'Alcohol (Markovnikov, no rearrangement)', productLong:'Oxymercuration gives Markovnikov hydration without carbocation rearrangement.',
        distractors:['Alcohol (anti-Markovnikov)', _D.diol_vic, _D.ether],
        mechanism:'Electrophilic Addition', explain:'Mercurinium ion intermediate (not a free cation) — water opens it at the more substituted C. NaBH₄ replaces Hg with H.' },
      { id:'a07', rxnId:7, reagent:'1) BH₃·THF', conditions:'2) H₂O₂, NaOH',
        productName:'Alcohol (anti-Markovnikov, syn)', productLong:'Hydroboration places OH on the less substituted carbon, same face.',
        distractors:['Alcohol (Markovnikov)', _D.diol_vic, _D.alkane],
        mechanism:'Concerted syn Addition', explain:'B and H add to the same face; B goes to less hindered C. H₂O₂/NaOH replaces B with OH with retention.' },
      { id:'a08', rxnId:8, reagent:'H₂', conditions:'Pd/C',
        productName:'Alkane (syn addition)', productLong:'Both H atoms add to the same face on the metal surface.',
        distractors:[_D.alc1, _D.diol_vic, _D.diene],
        mechanism:'Heterogeneous Reduction', explain:'H₂ adsorbs and splits on the Pd surface; the alkene binds and both H atoms transfer to the same face.' },
      { id:'a09', rxnId:9, reagent:'mCPBA', conditions:'CH₂Cl₂',
        productName:_D.epoxide, productLong:'Single-step syn addition of an O across the π bond.',
        distractors:[_D.diol_vic, _D.ket, 'Carboxylic acid'],
        mechanism:'Concerted Electrophilic Addition', explain:'mCPBA delivers an O to one face of the alkene in a concerted, butterfly-shaped transition state.' },
      { id:'a10', rxnId:11, reagent:'OsO₄ (cat.), NMO', conditions:'or KMnO₄ (cold, dilute)',
        productName:'cis-1,2-diol (syn)', productLong:'Both OH groups added to the same face of the alkene.',
        distractors:['trans-1,2-diol (anti)', _D.epoxide, _D.ket],
        mechanism:'Concerted Oxidative Addition', explain:'OsO₄ forms a 5-membered osmate ester across the alkene; hydrolysis releases the syn diol.' },
      { id:'a11', rxnId:12, reagent:'1) mCPBA', conditions:'2) H₃O⁺',
        productName:'trans-1,2-diol (anti)', productLong:'Epoxidation then acid-catalyzed water opening: trans diol.',
        distractors:['cis-1,2-diol (syn)', 'Halohydrin', _D.ket],
        mechanism:'Electrophilic Addition then Ring Opening', explain:'mCPBA gives the epoxide; H₃O⁺ opens it from the face opposite the O — net anti addition of two OHs.' },
      { id:'a12', rxnId:13, reagent:'1) O₃', conditions:'2) (CH₃)₂S or Zn/H₂O',
        productName:'Aldehydes and/or ketones', productLong:'C=C cleaved; each carbon keeps its hydrogens (or alkyls).',
        distractors:['Carboxylic acids', _D.diol_vic, _D.epoxide],
        mechanism:'Oxidative Cleavage', explain:'Ozone forms an ozonide; reductive workup (Me₂S or Zn) cleaves it to two carbonyls. =CHR → RCHO, =CR₂ → R₂C=O.' },
      { id:'a13', rxnId:14, reagent:'1) O₃', conditions:'2) H₂O₂',
        productName:'Carboxylic acids', productLong:'Oxidative workup pushes any aldehyde all the way to a carboxylic acid.',
        distractors:['Aldehydes and ketones', _D.diol_vic, _D.alc1],
        mechanism:'Oxidative Cleavage', explain:'Ozonide forms as before; H₂O₂ further oxidizes any =CHR fragment past the aldehyde stage to RCOOH (=CH₂ → CO₂).' },
      { id:'a14', rxnId:15, reagent:'NBS', conditions:'CCl₄, hν or ROOR',
        productName:'Allylic bromide', productLong:'Br replaces an allylic (not vinyl) H.',
        distractors:['Vinyl bromide', _D.rxvic, _D.epoxide],
        mechanism:'Radical Substitution', explain:'NBS supplies a low, steady concentration of Br•. The radical abstracts the weakest C–H (allylic), then HBr/NBS hands off a Br to the allylic radical.' },
      { id:'a15', rxnId:16, reagent:'CH₂I₂, Zn(Cu)', conditions:'(Simmons–Smith)',
        productName:_D.cyclopropane, productLong:'A CH₂ unit inserts across the π bond, syn.',
        distractors:[_D.epoxide, _D.alc1, _D.diol_vic],
        mechanism:'Concerted Carbene Addition', explain:'The Zn-carbenoid delivers :CH₂ to the same face of the alkene in a single concerted step — forms a new 3-membered ring.' },
      { id:'a16', rxnId:146, reagent:'PdCl₂, CuCl₂, O₂', conditions:'H₂O (Wacker)',
        productName:'Methyl ketone (Markovnikov)', productLong:'Terminal alkene → methyl ketone, no rearrangement.',
        distractors:[_D.ald, _D.alc1, _D.acid],
        mechanism:'TM-Catalyzed Oxidation', explain:'Pd(II) activates the terminal alkene; water attacks at the more substituted C; β-hydride elimination/tautomerization gives the methyl ketone. Cu/O₂ reoxidizes Pd.' },
      { id:'a17', rxnId:147, reagent:'Grubbs catalyst (Ru)', conditions:'CH₂Cl₂',
        productName:'New alkenes (metathesis)', productLong:'Alkylidene groups swap between two alkenes; small alkene (often ethylene) leaves.',
        distractors:[_D.cyclopropane, _D.alkane, _D.diol_vic],
        mechanism:'Metal-Carbene [2+2]', explain:'Ru-carbene forms a metallacyclobutane with one alkene, breaks apart the other way, then repeats with the second alkene — net swap of alkylidenes.' },
    ],
  },

  /* ═══════════ 2. ALKYNE ═══════════ */
  alkyne: {
    id: 'alkyne',
    label: 'Alkyne',
    subtitle: 'C≡C',
    trunkMolecule: null,
    blurb: 'Two π bonds. One equivalent of reagent gives a vinyl product; two equivalents go all the way through.',
    branches: [
      { id:'y01', rxnId:17, reagent:'HX (1 equiv)', conditions:'',
        productName:'Vinyl halide (Markovnikov)', productLong:'X on the more substituted C, alkene retained.',
        distractors:[_D.rxgem, _D.rxvic, _D.alkene],
        mechanism:'Electrophilic Addition', explain:'Just like alkene HX addition: protonate to the more stable vinyl cation, capture X⁻.' },
      { id:'y02', rxnId:18, reagent:'HX (2 equiv)', conditions:'',
        productName:_D.rxgem, productLong:'Both halogens end up on the same carbon (the more substituted one).',
        distractors:['Vinyl halide', _D.rxvic, _D.alkane],
        mechanism:'Electrophilic Addition (×2)', explain:'First HX gives a vinyl halide; the second adds Markovnikov again, putting both Xs on the same (more substituted) carbon.' },
      { id:'y03', rxnId:19, reagent:'X₂ (1 equiv)', conditions:'',
        productName:'trans dihaloalkene', productLong:'Two halogens add anti across one π bond.',
        distractors:[_D.rxvic, 'Tetrahaloalkane', _D.alkane],
        mechanism:'Electrophilic Addition', explain:'Halonium-style addition leaves an alkene with halogens on opposite faces.' },
      { id:'y04', rxnId:20, reagent:'X₂ (2 equiv)', conditions:'',
        productName:'Tetrahaloalkane', productLong:'All four halogens added (1,1,2,2-tetrahalo).',
        distractors:[_D.rxvic, _D.rxgem, _D.alkene],
        mechanism:'Electrophilic Addition (×2)', explain:'Each π bond is halogenated in turn; second addition is slower but goes to completion with excess X₂.' },
      { id:'y05', rxnId:21, reagent:'H₂O, H₂SO₄', conditions:'HgSO₄ (cat.)',
        productName:'Methyl ketone (Markovnikov)', productLong:'Terminal alkyne → methyl ketone via enol tautomerization.',
        distractors:[_D.ald, _D.diol_gem, _D.alc2],
        mechanism:'Addition + Tautomerization', explain:'Hg²⁺ activates the alkyne; Markovnikov hydration gives an enol that tautomerizes to the more stable ketone.' },
      { id:'y06', rxnId:22, reagent:'1) Sia₂BH or 9-BBN', conditions:'2) H₂O₂, NaOH',
        productName:'Aldehyde (anti-Markovnikov)', productLong:'Terminal alkyne → aldehyde via enol tautomerization.',
        distractors:['Methyl ketone', _D.alc1, _D.acid],
        mechanism:'Concerted syn Addition + Tautomerization', explain:'Bulky borane adds B to the less substituted carbon; oxidation gives the anti-Markovnikov enol, which tautomerizes to the aldehyde.' },
      { id:'y07', rxnId:23, reagent:'H₂, Lindlar', conditions:'Pd/CaCO₃, quinoline',
        productName:'cis-alkene', productLong:'Stops at the alkene; both H atoms add to the same face.',
        distractors:['trans-alkene', _D.alkane, _D.diene],
        mechanism:'Heterogeneous Reduction', explain:'Poisoned palladium can deliver one H₂ across the alkyne to give the cis-alkene but won\u2019t reduce further.' },
      { id:'y08', rxnId:24, reagent:'Na (or Li)', conditions:'liq. NH₃',
        productName:'trans-alkene', productLong:'Anti addition via a radical-anion mechanism.',
        distractors:['cis-alkene', _D.alkane, 'Vinyl halide'],
        mechanism:'Dissolving Metal Reduction', explain:'Electron transfer + protonation steps occur on opposite faces, locking the trans geometry in the vinyl anion intermediate.' },
      { id:'y09', rxnId:25, reagent:'1) NaNH₂', conditions:'2) primary R-X',
        productName:'Internal alkyne', productLong:'Terminal alkyne extended by an alkyl group.',
        distractors:[_D.alkene, _D.alkane, _D.amine1],
        mechanism:'SN2', explain:'NaNH₂ deprotonates the terminal alkyne (pKa ≈ 25). The acetylide carbanion then displaces X from a primary alkyl halide.' },
    ],
  },

  /* ═══════════ 3. ALKYL HALIDE ═══════════ */
  alkyl_halide: {
    id: 'alkyl_halide',
    label: 'Alkyl halide',
    subtitle: 'R–X',
    trunkMolecule: '1-bromopropane',
    blurb: 'C–X bond is the leaving group. Substitution and elimination compete; substrate class and conditions decide which wins.',
    branches: [
      { id:'h01', rxnId:26, reagent:'Strong Nu⁻', conditions:'1° (or 2°), polar aprotic',
        productName:'Substitution (inversion)', productLong:'Nucleophile replaces X with inversion of configuration at C.',
        distractors:['Elimination (alkene)', 'Substitution (racemized)', _D.alkane],
        mechanism:'SN2', explain:'Backside attack by Nu⁻ at the carbon bearing X. One concerted step — rate depends on both [RX] and [Nu].' },
      { id:'h02', rxnId:27, reagent:'Weak Nu', conditions:'3°, polar protic',
        productName:'Substitution (racemic)', productLong:'Free carbocation can be attacked from either face → loss of stereochem.',
        distractors:['Substitution (inversion)', 'Alkene (Zaitsev)', _D.alkane],
        mechanism:'SN1', explain:'Slow ionization to a 3° carbocation; weak nucleophile attacks the planar cation from either face. Two-step.' },
      { id:'h03', rxnId:28, reagent:'Strong, bulky base', conditions:'KOtBu, NaOEt; heat',
        productName:'Alkene (Zaitsev, anti-periplanar)', productLong:'β-H removed anti to X — more substituted alkene wins.',
        distractors:['Alkene (Hofmann)', 'Substitution (inversion)', _D.alkane],
        mechanism:'E2', explain:'One concerted step: base grabs β-H while C–X breaks. Requires anti-periplanar geometry.' },
      { id:'h04', rxnId:29, reagent:'Weak base', conditions:'3°, heat, polar protic',
        productName:'Alkene (Zaitsev)', productLong:'Cation forms, then loses β-H to give the more substituted alkene.',
        distractors:['Alkene (Hofmann)', 'Substitution', _D.alkane],
        mechanism:'E1', explain:'Ionization to a 3° cation (slow), then any weak base removes a β-H to form the more stable alkene.' },
      { id:'h05', rxnId:30, reagent:'Mg(0)', conditions:'dry ether or THF',
        productName:'Grignard reagent (R–MgX)', productLong:'A nucleophilic, basic organometallic.',
        distractors:['Alcohol', 'Alkene', 'Alkyl tosylate'],
        mechanism:'Oxidative Addition (radical)', explain:'Mg inserts into the C–X bond via a single-electron transfer mechanism. The product is a carbanion equivalent.' },
      { id:'h06', rxnId:36, reagent:'2 Li(0)', conditions:'dry ether or THF',
        productName:'Organolithium (R–Li)', productLong:'Stronger, more basic cousin of the Grignard reagent.',
        distractors:['Alcohol', 'Aldehyde', 'Lithium alkoxide'],
        mechanism:'Oxidative Addition (radical)', explain:'Two Li atoms insert: one ends up as R–Li, the other as LiX. R–Li is even more carbanion-like than RMgX.' },
      { id:'h07', rxnId:154, reagent:'NaSH (or thiourea)', conditions:'',
        productName:'Thiol (R–SH)', productLong:'S is the new nucleophile — installs an –SH group.',
        distractors:['Disulfide', 'Sulfonate ester', 'Sulfide (R–S–R)'],
        mechanism:'SN2', explain:'HS⁻ is a soft, polarizable nucleophile — excellent at SN2 on primary alkyl halides.' },
    ],
  },

  /* ═══════════ 4. ARENE (BENZENE-LIKE) ═══════════ */
  arene: {
    id: 'arene',
    label: 'Arene',
    subtitle: 'Ar–H',
    trunkMolecule: 'benzene',
    blurb: 'Aromatic π system is the nucleophile. Loses an H and keeps its aromaticity (substitution, not addition).',
    branches: [
      { id:'r01', rxnId:38, reagent:'X₂', conditions:'FeX₃',
        productName:'Aryl halide', productLong:'One H on the ring is replaced by X.',
        distractors:[_D.rxvic, _D.cyclopropane, 'Cyclohexa-1,3-diene'],
        mechanism:'EAS', explain:'FeX₃ polarizes X₂ to make X⁺. Ring attacks; H⁺ leaves to rebuild aromaticity.' },
      { id:'r02', rxnId:39, reagent:'HNO₃', conditions:'H₂SO₄',
        productName:'Nitroarene', productLong:'One H on the ring is replaced by NO₂.',
        distractors:['Aniline (NH₂ ring)', 'Phenol (OH ring)', 'Cyclohexanone'],
        mechanism:'EAS', explain:'Mixed acid generates NO₂⁺ (nitronium). Ring attacks N; deprotonation restores the aromatic system.' },
      { id:'r03', rxnId:40, reagent:'H₂SO₄ (fuming)', conditions:'or SO₃/H₂SO₄',
        productName:'Arylsulfonic acid', productLong:'–SO₃H group installed on the ring (reversible).',
        distractors:['Arylsulfide', 'Aryl ether', 'Nitroarene'],
        mechanism:'EAS', explain:'SO₃ is the electrophile. The whole sequence is reversible — heating in dilute aq. acid removes the SO₃H.' },
      { id:'r04', rxnId:41, reagent:'R–X', conditions:'AlCl₃',
        productName:'Alkylbenzene', productLong:'Alkyl group added to ring; prone to polyalkylation and rearrangement.',
        distractors:['Aryl ketone', 'Phenol', 'Diaryl ether'],
        mechanism:'EAS (Friedel–Crafts Alkylation)', explain:'AlCl₃ ionizes R–X to a carbocation. Ring attacks the cation; deprotonation rebuilds aromaticity. Alkyl groups activate the ring → over-alkylation.' },
      { id:'r05', rxnId:42, reagent:'R(C=O)Cl', conditions:'AlCl₃',
        productName:'Aryl ketone', productLong:'Acyl group on ring — no rearrangement, no over-acylation.',
        distractors:[_D.alc1, 'Alkylbenzene', _D.ester],
        mechanism:'EAS (Friedel–Crafts Acylation)', explain:'AlCl₃ generates an acylium ion R-C≡O⁺. Ring attacks. The product ketone deactivates the ring, so the reaction stops after one acylation.' },
      { id:'r06', rxnId:43, reagent:'Strong Nu⁻', conditions:'EWG ortho/para to X, heat',
        productName:'Substituted arene (Nu replaces X)', productLong:'X leaves via the Meisenheimer (cyclohexadienyl) intermediate.',
        distractors:['Sulfonic acid', _D.diene, _D.cyclopropane],
        mechanism:'SNAr', explain:'Nu⁻ adds to ring giving a stabilized anion (Meisenheimer complex); X⁻ leaves to restore aromaticity. Requires strong EWG ortho/para to X.' },
      { id:'r07', rxnId:44, reagent:'Na or Li', conditions:'liq. NH₃, ROH',
        productName:'1,4-cyclohexadiene', productLong:'Two H atoms added at the 1,4 positions of the ring.',
        distractors:['Cyclohexane', 'Cyclohexanone', '1,3-cyclohexadiene'],
        mechanism:'Birch Reduction', explain:'Solvated electron adds to ring; protonation; second electron; second protonation. EDG keep C=C at substituted positions; EWG away from them.' },
      { id:'r08', rxnId:45, reagent:'KMnO₄, heat', conditions:'(or K₂Cr₂O₇)',
        productName:'Benzoic acid', productLong:'Any benzylic alkyl chain → COOH (so long as a benzylic H exists).',
        distractors:[_D.ald, _D.ket, 'Phenol'],
        mechanism:'Side-Chain Oxidation', explain:'KMnO₄ chews any benzylic C–H all the way down to the ring carbon, giving ArCOOH regardless of original chain length.' },
      { id:'r09', rxnId:46, reagent:'NBS', conditions:'CCl₄, hν or ROOR',
        productName:'Benzylic bromide', productLong:'Br on the carbon directly attached to the ring.',
        distractors:['Aryl bromide (Br on ring)', 'Vinyl bromide', _D.rxvic],
        mechanism:'Radical Substitution', explain:'NBS supplies a low concentration of Br•; the resonance-stabilized benzylic radical wins. Br• then quenches the radical.' },
      { id:'r10', rxnId:148, reagent:'Alkene', conditions:'Pd(0), base',
        productName:'Substituted alkene (trans)', productLong:'Aryl group replaces a vinyl H; trans isomer preferred.',
        distractors:[_D.cyclopropane, _D.alkane, 'Biaryl'],
        mechanism:'Heck (Pd cross-coupling)', explain:'Pd(0) oxidatively adds Ar–X; alkene inserts; β-hydride elimination gives the new aryl alkene. Base regenerates Pd(0).' },
      { id:'r11', rxnId:149, reagent:'Ar′-B(OH)₂', conditions:'Pd(0), base',
        productName:'Biaryl', productLong:'New Ar–Ar′ bond — two aromatic rings joined.',
        distractors:['Alkylbenzene', 'Diaryl ether', _D.amine1],
        mechanism:'Suzuki coupling', explain:'Pd oxidative addition + transmetalation with arylboronic acid + reductive elimination form the new C–C bond.' },
      { id:'r12', rxnId:150, reagent:'Ar′-SnR₃', conditions:'Pd(0)',
        productName:'Biaryl (or aryl alkenyl)', productLong:'Similar to Suzuki but with an organotin partner.',
        distractors:['Alkylbenzene', 'Aryl ketone', _D.amine1],
        mechanism:'Stille coupling', explain:'Pd oxidative addition + transmetalation with Ar′-SnR₃ + reductive elimination. Tolerates more functional groups than Suzuki.' },
      { id:'r13', rxnId:151, reagent:'HC≡C–R', conditions:'Pd(0)/CuI, amine base',
        productName:'Internal aryl alkyne', productLong:'Ar–C≡C–R, formed from aryl halide and terminal alkyne.',
        distractors:[_D.alkene, 'Biaryl', _D.cyclopropane],
        mechanism:'Sonogashira coupling', explain:'Cu activates the terminal alkyne as Cu-acetylide; Pd does oxidative addition / transmetalation / reductive elimination.' },
    ],
  },

  /* ═══════════ 5. ARYL AMINE → DIAZONIUM ═══════════ */
  diazonium: {
    id: 'diazonium',
    label: 'Aryl diazonium',
    subtitle: 'Ar–N₂⁺',
    trunkMolecule: null,
    blurb: 'Generated from primary aryl amine + NaNO₂/HCl at 0 °C. N₂ is a phenomenal leaving group — many groups can take its place.',
    branches: [
      { id:'d01', rxnId:47, reagent:'NaNO₂, HCl, 0 °C', conditions:'(from Ar-NH₂)',
        productName:'Aryl diazonium salt (Ar-N₂⁺)', productLong:'Primary aromatic amine becomes a diazonium salt.',
        distractors:[_D.ester, _D.nitrile, 'Nitroarene'],
        mechanism:'Electrophilic Addition to N', explain:'HONO (in situ from NaNO₂/HCl) attacks the amine; dehydration leaves Ar-N₂⁺. Stable only at low T.' },
      { id:'d02', rxnId:48, reagent:'CuX (X = Cl, Br, CN)', conditions:'or KI',
        productName:'Aryl halide (or aryl nitrile)', productLong:'Cu(I) salt replaces N₂ with X (or CN).',
        distractors:['Phenol', _D.amine1, 'Arene (H replaces N₂)'],
        mechanism:'Sandmeyer (radical, Cu-catalyzed)', explain:'Cu(I) transfers X• via single-electron steps. KI works without Cu via Ar-I.' },
      { id:'d03', rxnId:49, reagent:'H₂O', conditions:'heat',
        productName:'Phenol', productLong:'OH replaces N₂.',
        distractors:[_D.amine1, 'Aryl halide', 'Aniline'],
        mechanism:'SN1-like (via arenium)', explain:'Heat ejects N₂ as a gas (great leaving group), giving an aryl cation that water captures.' },
      { id:'d04', rxnId:50, reagent:'H₃PO₂', conditions:'(hypophosphorous acid)',
        productName:'Arene (H replaces N₂)', productLong:'Net: amine group has been deleted from the ring.',
        distractors:[_D.amine1, 'Phenol', 'Aryl halide'],
        mechanism:'Radical Reduction', explain:'A radical chain replaces N₂ with H. Useful trick: install NH₂ as a directing group, then remove it.' },
      { id:'d05', rxnId:51, reagent:'H₂, Pd/C', conditions:'(or Fe/HCl, Sn/HCl)',
        productName:_D.amine1+' (Ar-NH₂)', productLong:'NO₂ group reduced to NH₂.',
        distractors:[_D.ald, 'Nitroso (Ar-NO)', 'Hydroxylamine (Ar-NHOH)'],
        mechanism:'Reduction (multistep)', explain:'Six electrons + six protons reduce NO₂ to NH₂ on the way to Ar-NH₂. Common precursor to diazonium chemistry.' },
    ],
  },

  /* ═══════════ 6. ALCOHOL ═══════════ */
  alcohol: {
    id: 'alcohol',
    label: 'Alcohol',
    subtitle: 'R–OH',
    trunkMolecule: 'propan-2-ol',
    blurb: 'OH is a poor leaving group — activate it first (protonate, convert to halide, tosylate, chromate ester). Or just oxidize it.',
    branches: [
      { id:'o01', rxnId:52, reagent:'H₂SO₄ (or H₃PO₄)', conditions:'heat',
        productName:'Alkene (Zaitsev)', productLong:'Acid-catalyzed dehydration: 3° > 2° >> 1°.',
        distractors:[_D.alkane, _D.ket, _D.ester],
        mechanism:'E1', explain:'Acid protonates OH (now H₂O is the LG); ionization to cation; β-H lost to give the more substituted alkene.' },
      { id:'o02', rxnId:53, reagent:'HX', conditions:'(HI > HBr > HCl); acid, heat',
        productName:'Alkyl halide', productLong:'Direct OH → X via protonation and substitution.',
        distractors:[_D.alkene, _D.ether, _D.ester],
        mechanism:'SN1 (3°) or SN2 (1°)', explain:'H⁺ converts OH to OH₂⁺ (a good LG). 1° goes SN2 (X⁻ does backside attack); 3° goes SN1 (cation forms, X⁻ captures).' },
      { id:'o03', rxnId:54, reagent:'SOCl₂', conditions:'pyridine',
        productName:'Alkyl chloride', productLong:'Inversion at C (or retention with pyridine via chlorosulfite).',
        distractors:[_D.alkene, 'Sulfonate', _D.ester],
        mechanism:'SN2', explain:'OH attacks S; Cl⁻ then displaces the chlorosulfite leaving group at C — inversion. Byproducts: SO₂ + HCl.' },
      { id:'o04', rxnId:55, reagent:'PBr₃', conditions:'',
        productName:'Alkyl bromide (inversion)', productLong:'OH → Br with inversion of configuration.',
        distractors:[_D.alkene, _D.ester, _D.ether],
        mechanism:'SN2', explain:'O attacks P; Br⁻ then does backside SN2 on C, displacing the phosphite leaving group. Inversion.' },
      { id:'o05', rxnId:56, reagent:'TsCl', conditions:'pyridine',
        productName:'Tosylate (R–OTs)', productLong:'OH activated as a great leaving group — configuration retained at C.',
        distractors:[_D.alkene, _D.ester, 'Sulfide'],
        mechanism:'Nucleophilic Substitution at S', explain:'O attacks the S of TsCl; Cl⁻ leaves. The C-O bond is untouched, so stereochemistry at C is unchanged.' },
      { id:'o06', rxnId:57, reagent:'PCC', conditions:'CH₂Cl₂  (1° alcohol)',
        productName:_D.ald, productLong:'Stops at the aldehyde — does not over-oxidize.',
        distractors:[_D.acid, _D.ket, _D.alkene],
        mechanism:'Oxidation (mild)', explain:'PCC forms a chromate ester; β-elimination of Cr/H gives the C=O. Anhydrous conditions prevent further oxidation.' },
      { id:'o07', rxnId:58, reagent:'1) (COCl)₂, DMSO', conditions:'2) Et₃N, –78 °C (Swern)',
        productName:_D.ald, productLong:'Very mild oxidation; tolerates sensitive functional groups.',
        distractors:[_D.acid, _D.ester, _D.alkene],
        mechanism:'Oxidation (mild)', explain:'Activated DMSO becomes an alkoxysulfonium; Et₃N deprotonates and E2-like elimination gives the carbonyl. Byproduct: DMS.' },
      { id:'o08', rxnId:59, reagent:'PCC (or Jones / Swern)', conditions:'(2° alcohol)',
        productName:_D.ket, productLong:'2° alcohol → ketone (only option since C already has only one H).',
        distractors:[_D.ald, _D.acid, _D.alkene],
        mechanism:'Oxidation', explain:'Any standard alcohol oxidant cleanly oxidizes a 2° alcohol to a ketone; no over-oxidation possible.' },
      { id:'o09', rxnId:60, reagent:'KMnO₄ or CrO₃/H₂SO₄', conditions:'(1° alcohol)',
        productName:_D.acid, productLong:'Powerful oxidants take 1° alcohol all the way to RCOOH.',
        distractors:[_D.ald, _D.ket, _D.ester],
        mechanism:'Oxidation', explain:'Aqueous oxidants don\u2019t stop at the aldehyde — the hydrate is oxidized to the acid.' },
      { id:'o10', rxnId:133, reagent:'Dess–Martin periodinane', conditions:'CH₂Cl₂',
        productName:_D.ald+' (or '+_D.ket+')', productLong:'Modern mild alternative to PCC / Swern.',
        distractors:[_D.acid, _D.ester, _D.alkene],
        mechanism:'Oxidation (mild)', explain:'DMP is a hypervalent iodine reagent that delivers oxygen and removes one H from C. Stops at aldehyde / ketone.' },
      { id:'o11', rxnId:61, reagent:'RCOOH + H₂SO₄', conditions:'heat (Fischer)',
        productName:_D.ester, productLong:'Acid + alcohol = ester + water (equilibrium).',
        distractors:[_D.amide, _D.ether, _D.alc1],
        mechanism:'Acid-Catalyzed PADPED', explain:'Protonate carbonyl, alcohol adds, proton transfer, water leaves, deprotonate. Drive forward with excess alcohol or Dean–Stark.' },
      { id:'o12', rxnId:62, reagent:'R′-X', conditions:'after NaH / KOH (Williamson)',
        productName:_D.ether, productLong:'Alkoxide displaces X from a primary alkyl halide.',
        distractors:[_D.ester, _D.alc1, _D.amine1],
        mechanism:'SN2', explain:'Base deprotonates the alcohol; the alkoxide then SN2s on R′-X. The alkyl halide partner must be 1° (or methyl).' },
      { id:'o13', rxnId:66, reagent:'RCOOH, DEAD, PPh₃', conditions:'(Mitsunobu)',
        productName:'Inverted ester (or N-alkyl)', productLong:'Alcohol\u2192 ester with INVERSION of configuration at C.',
        distractors:[_D.ether, _D.alkene, _D.amide],
        mechanism:'SN2', explain:'PPh₃ + DEAD activate the alcohol as an oxyphosphonium leaving group; the carboxylate (deprotonated by hydrazide) then SN2s on C with inversion.' },
      { id:'o14', rxnId:10, reagent:'Ti(OiPr)₄, DET, TBHP', conditions:'(Sharpless; allylic alcohol)',
        productName:'Chiral epoxide', productLong:'Asymmetric epoxidation of the alkene of an allylic alcohol.',
        distractors:['Racemic epoxide', _D.diol_vic, _D.ket],
        mechanism:'Asymmetric Concerted Addition', explain:'Ti–tartrate complex directs O transfer to one face of the alkene preferentially — predictable enantioselectivity.' },
    ],
  },

  /* ═══════════ 7. ALDEHYDE / KETONE ═══════════ */
  carbonyl: {
    id: 'carbonyl',
    label: 'Aldehyde / Ketone',
    subtitle: 'R–C=O',
    trunkMolecule: 'cyclohexanone',
    blurb: 'Electrophilic carbonyl C and α-H acidity. The carbonyl gets attacked by nucleophiles; the α-C becomes a nucleophile via the enol/enolate.',
    branches: [
      { id:'k01', rxnId:67, reagent:'H₂O', conditions:'acid or base',
        productName:_D.diol_gem, productLong:'Hydrate — equilibrium usually favors the C=O for ketones.',
        distractors:[_D.acetal, _D.alc1, _D.diol_vic],
        mechanism:'Nucleophilic Addition', explain:'Water adds across C=O. Strained / electron-poor C=O (e.g. formaldehyde, chloral) shift the equilibrium toward the hydrate.' },
      { id:'k02', rxnId:68, reagent:'2 R′OH', conditions:'H⁺ (cat.), Dean-Stark',
        productName:_D.acetal, productLong:'C(OR)₂ in place of C=O — useful as a protecting group.',
        distractors:[_D.ester, _D.ether, _D.imine],
        mechanism:'Acid-Catalyzed PADPED', explain:'Protonate C=O, alcohol adds, lose water, second alcohol adds, deprotonate. Reversible — use anhydrous acid to remove later.' },
      { id:'k03', rxnId:69, reagent:'R-NH₂ (1° amine)', conditions:'H⁺ (cat.), heat',
        productName:_D.imine, productLong:'C=N replaces C=O.',
        distractors:[_D.enamine, _D.amine2, _D.amide],
        mechanism:'Addition-Elimination', explain:'Amine adds to C=O to form a hemiaminal; proton transfer and loss of water give the imine. Use pH ~5 for max rate.' },
      { id:'k04', rxnId:70, reagent:'R₂NH (2° amine)', conditions:'H⁺ (cat.), heat',
        productName:_D.enamine, productLong:'C=C with NR₂ on one end — there is no N-H for a stable imine.',
        distractors:[_D.imine, _D.amide, _D.amine2],
        mechanism:'Addition-Elimination', explain:'Same addition step as imine; without N-H, water leaves with a β-C-H to give the enamine. Used as a soft nucleophile (Stork).' },
      { id:'k05', rxnId:71, reagent:'HCN (or NaCN / H⁺)', conditions:'',
        productName:_D.cyanohydrin, productLong:'CN and OH on the same carbon.',
        distractors:[_D.nitrile, _D.acid, _D.amide],
        mechanism:'Nucleophilic Addition', explain:'CN⁻ adds to C=O; protonation gives the cyanohydrin. The CN can later be hydrolyzed to a carboxylic acid.' },
      { id:'k06', rxnId:72, reagent:'NaBH₄', conditions:'MeOH or EtOH',
        productName:_D.alc1+' or '+_D.alc2, productLong:'Aldehyde → 1° OH, ketone → 2° OH. Does not touch esters/acids.',
        distractors:[_D.alkane, _D.ether, _D.imine],
        mechanism:'Hydride Addition', explain:'H⁻ from BH₄⁻ adds to C=O; protonation in the workup gives the alcohol. Mild — selective for aldehydes/ketones.' },
      { id:'k07', rxnId:73, reagent:'1) LiAlH₄', conditions:'2) H₂O',
        productName:_D.alc1+' or '+_D.alc2, productLong:'LiAlH₄ is the more aggressive cousin of NaBH₄.',
        distractors:[_D.alkane, _D.ether, _D.amine1],
        mechanism:'Hydride Addition', explain:'H⁻ from AlH₄⁻ adds to C=O. LiAlH₄ also reduces esters, acids, amides, nitriles — much broader scope than NaBH₄.' },
      { id:'k08', rxnId:74, reagent:'Ph₃P=CR₂ (ylide)', conditions:'',
        productName:'Alkene (C=C replaces C=O)', productLong:'Phosphorus ylide swaps =O for =CR₂.',
        distractors:[_D.alc1, _D.acetal, _D.epoxide],
        mechanism:'Wittig ([2+2] / [2+2] retro)', explain:'Ylide and C=O form a 4-membered oxaphosphetane that collapses to alkene + Ph₃P=O.' },
      { id:'k09', rxnId:75, reagent:'NH₂NH₂, KOH', conditions:'ethylene glycol, heat',
        productName:'Alkane (C=O → CH₂)', productLong:'Full deoxygenation under basic conditions.',
        distractors:[_D.alc1, _D.amine1, _D.amide],
        mechanism:'Wolff–Kishner', explain:'Hydrazone forms; KOH/heat drives loss of N₂ via a carbanion intermediate. Works under base.' },
      { id:'k10', rxnId:76, reagent:'Zn(Hg), HCl', conditions:'heat',
        productName:'Alkane (C=O → CH₂)', productLong:'Acidic version of Wolff–Kishner.',
        distractors:[_D.alc1, _D.alkene, 'Hydrazone'],
        mechanism:'Clemmensen Reduction', explain:'Reduction on the Zn(Hg) surface in strong acid takes the C=O to CH₂. Complementary to Wolff–Kishner for acid-sensitive substrates.' },
      { id:'k11', rxnId:77, reagent:'mCPBA', conditions:'(or peracid)',
        productName:_D.ester, productLong:'Baeyer–Villiger: O inserts next to C=O; more substituted group migrates.',
        distractors:[_D.epoxide, _D.acid, _D.amide],
        mechanism:'Oxidative Rearrangement', explain:'Peracid adds to C=O; migration of the more substituted R from C to O, with loss of the peracid carboxylate. From aldehyde → formate ester.' },
      { id:'k12', rxnId:78, reagent:'Ag(NH₃)₂⁺', conditions:'(Tollens — aldehyde only)',
        productName:'Carboxylate + Ag⁰ (mirror)', productLong:'Diagnostic test: aldehyde oxidized to acid; ketones do nothing.',
        distractors:[_D.alc1, _D.alkene, _D.ester],
        mechanism:'Oxidation', explain:'Ag(I) is reduced to metallic Ag (the "silver mirror"); aldehyde\u2019s C-H is oxidized to C-OH.' },
      { id:'k13', rxnId:101, reagent:'X₂', conditions:'H₃O⁺ (cat.); has α-H',
        productName:'α-halo carbonyl (monohalogenated)', productLong:'Acid catalysis halogenates once per α-H position.',
        distractors:['Polyhalo carbonyl', _D.diol_gem, _D.alkene],
        mechanism:'α-Substitution via Enol', explain:'Acid forms an enol; X₂ adds to the enol; tautomerization back to the now-α-halo carbonyl. Each α-H is independently reactive.' },
      { id:'k14', rxnId:102, reagent:'X₂, NaOH (excess)', conditions:'(methyl ketone)',
        productName:'CHX₃ + RCOO⁻ (haloform)', productLong:'Methyl group is exhaustively halogenated, then cleaved off.',
        distractors:['α-halo ketone', _D.ester, _D.acid],
        mechanism:'α-Substitution via Enolate + Cleavage', explain:'Base forms the enolate; rapid trihalogenation; OH⁻ attacks the now-electrophilic carbonyl and CX₃⁻ leaves as the haloform.' },
      { id:'k15', rxnId:103, reagent:'LDA', conditions:'THF, –78 °C',
        productName:'Kinetic enolate', productLong:'Less substituted enolate, formed irreversibly.',
        distractors:['Thermodynamic enolate', _D.amide, _D.amine1],
        mechanism:'Deprotonation', explain:'Bulky LDA grabs the most accessible α-H (the less hindered one) and doesn\u2019t equilibrate at low T.' },
      { id:'k16', rxnId:104, reagent:'Enolate + R-X', conditions:'',
        productName:'α-alkyl carbonyl', productLong:'New C-C bond at the α-carbon.',
        distractors:['O-alkyl carbonyl (enol ether)', _D.ester, _D.alkene],
        mechanism:'SN2 (at R-X)', explain:'The enolate is the nucleophile; primary alkyl halide is the electrophile. Backside attack at C of R-X.' },
      { id:'k17', rxnId:105, reagent:'NaOH (aq), 0 °C', conditions:'(has α-H)',
        productName:'β-hydroxy carbonyl', productLong:'Aldol product — new C-C bond between α-C of one molecule and carbonyl-C of another.',
        distractors:['α,β-unsaturated carbonyl', _D.acetal, _D.epoxide],
        mechanism:'Aldol (enolate addition)', explain:'Mild base makes some enolate; enolate adds to the C=O of a second molecule; protonation gives the β-hydroxy carbonyl.' },
      { id:'k18', rxnId:106, reagent:'NaOH, heat', conditions:'(has α-H)',
        productName:'α,β-unsaturated carbonyl', productLong:'Aldol condensation: aldol product dehydrates.',
        distractors:['β-hydroxy carbonyl', _D.acetal, _D.epoxide],
        mechanism:'Aldol + E1cb', explain:'Same enolate addition, then under heat the β-OH leaves as the alkene forms (E1cb in basic conditions).' },
      { id:'k19', rxnId:111, reagent:'CH(COOR)₂CH₂ etc.', conditions:'amine cat. (Knoevenagel)',
        productName:'α,β-unsaturated dicarbonyl', productLong:'Aldol-style condensation from an active methylene compound.',
        distractors:[_D.acetal, 'β-hydroxy dicarbonyl', _D.epoxide],
        mechanism:'Addition-Elimination', explain:'Amine forms an enamine of the carbonyl; enamine attacks the active-methylene C, then β-elimination of amine + water gives the alkene.' },
      { id:'k20', rxnId:112, reagent:'CH₂O + R₂NH', conditions:'H⁺ cat. (Mannich)',
        productName:'β-amino carbonyl', productLong:'Three-component coupling: ketone + formaldehyde + amine.',
        distractors:[_D.acetal, _D.amide, _D.imine],
        mechanism:'Iminium + Enol Addition', explain:'Amine + CH₂O form an iminium ion; the enol of the ketone attacks it.' },
      { id:'k21', rxnId:116, reagent:'R₂NH + NaBH₃CN', conditions:'H⁺ (mild)',
        productName:_D.amine1+'/2°/3°', productLong:'New C-N bond at what was the carbonyl C.',
        distractors:[_D.imine, _D.amide, _D.alc1],
        mechanism:'Reductive Amination', explain:'Amine + C=O make an iminium; selective hydride source reduces just the iminium (not the unreacted ketone) to give the amine.' },
      { id:'k22', rxnId:134, reagent:'H₂SO₄, heat', conditions:'(1,2-diol)',
        productName:_D.ket+' (pinacolone)', productLong:'1,2-diol becomes a ketone via a 1,2-alkyl shift.',
        distractors:[_D.alkene, _D.epoxide, _D.diol_gem],
        mechanism:'Pinacol Rearrangement', explain:'Protonate OH; lose water to form cation; 1,2-alkyl/hydride shift to give a more-stabilized oxocarbenium; lose proton to give the ketone.' },
      { id:'k23', rxnId:135, reagent:'H₂SO₄ or PCl₅', conditions:'(oxime substrate)',
        productName:_D.amide+' (or lactam)', productLong:'Beckmann: anti R group migrates from C to N as water leaves.',
        distractors:[_D.imine, _D.amine1, _D.nitrile],
        mechanism:'Rearrangement', explain:'Protonation of oxime OH; group anti to OH migrates from C to N with loss of water; water rebinds to give the amide.' },
      { id:'k24', rxnId:136, reagent:'HS-CH₂-CH₂-SH', conditions:'BF₃ or H⁺',
        productName:'1,3-dithiane (thioacetal)', productLong:'Sulfur analog of acetal — stable to bases and nucleophiles.',
        distractors:[_D.acetal, _D.epoxide, _D.ether],
        mechanism:'Nucleophilic Addition', explain:'Analogous to acetal formation: protonate carbonyl, dithiol adds twice, lose water. Removed later by HgCl₂ or Raney Ni.' },
      { id:'k25', rxnId:138, reagent:'Al(OiPr)₃', conditions:'iPrOH (Meerwein-Ponndorf-Verley)',
        productName:_D.alc1+' (or '+_D.alc2+')', productLong:'Selective, reversible reduction of carbonyl.',
        distractors:[_D.alkane, _D.amine1, _D.ester],
        mechanism:'Hydride Transfer (Lewis acid)', explain:'iPrOH coordinates Al; a 6-membered transition state passes H⁻ from iPrO to C=O. Reversible — drive with excess iPrOH.' },
    ],
  },

  /* ═══════════ 8. CARBOXYLIC ACID ═══════════ */
  acid: {
    id: 'acid',
    label: 'Carboxylic acid',
    subtitle: 'R-COOH',
    trunkMolecule: 'acetic_acid',
    blurb: 'Acidic O-H, electrophilic C. Most acid-derivative chemistry runs through making OH a better leaving group first.',
    branches: [
      { id:'c01', rxnId:79, reagent:'SOCl₂ (or PCl₅, oxalyl Cl)', conditions:'',
        productName:'Acid chloride (R-COCl)', productLong:'Activates the carbonyl for further nucleophilic attack.',
        distractors:[_D.ester, _D.amide, 'Anhydride'],
        mechanism:'Nucleophilic Acyl Substitution', explain:'O of OH attacks S; tetrahedral intermediate; Cl⁻ replaces -OSO(Cl) leaving group. Byproducts: SO₂, HCl (great because they\u2019re gases).' },
      { id:'c02', rxnId:80, reagent:'Heat (intramolecular)', conditions:'or Cl-COR + carboxylate',
        productName:'Anhydride', productLong:'Two acyl groups bridged by O.',
        distractors:[_D.ester, _D.amide, _D.acid],
        mechanism:'Nucleophilic Acyl Substitution', explain:'For simple cyclic anhydrides, heat drives dehydration. For mixed anhydrides, an acyl chloride + carboxylate works.' },
      { id:'c03', rxnId:81, reagent:'1) LiAlH₄', conditions:'2) H₂O',
        productName:_D.alc1, productLong:'Acid → primary alcohol (C=O fully reduced to CH₂).',
        distractors:[_D.ald, _D.amine1, _D.ester],
        mechanism:'Hydride Reduction', explain:'LiAlH₄ first deprotonates the OH; then delivers two hydrides through an aldehyde intermediate to the primary alcohol.' },
      { id:'c04', rxnId:61, reagent:'R\u2019OH, H₂SO₄', conditions:'heat (Fischer)',
        productName:_D.ester, productLong:'Acid + alcohol = ester + water (equilibrium).',
        distractors:[_D.ether, _D.amide, _D.acid],
        mechanism:'Acid-Catalyzed PADPED', explain:'Same as in the alcohol tree — works from either direction. Use excess alcohol or Dean-Stark to drive forward.' },
      { id:'c05', rxnId:82, reagent:'Heat', conditions:'(β-keto acid)',
        productName:_D.ket+' + CO₂', productLong:'Loses CO₂ via a 6-membered cyclic TS.',
        distractors:[_D.alc2, _D.ald, _D.ester],
        mechanism:'Pericyclic Decarboxylation', explain:'β-keto acids decarboxylate by passing through a 6-membered ring where the keto O grabs an H as CO₂ leaves; tautomerize the enol to the ketone.' },
      { id:'c06', rxnId:83, reagent:'Heat', conditions:'(malonic-type diacid)',
        productName:'Monocarboxylic acid + CO₂', productLong:'Same trick as #82 but starting from a 1,3-diacid.',
        distractors:[_D.ald, _D.alc1, _D.ester],
        mechanism:'Pericyclic Decarboxylation', explain:'One COOH acts as the "ketone" in the 6-membered TS that ejects the other CO₂.' },
      { id:'c07', rxnId:84, reagent:'Br₂, PBr₃ (cat.)', conditions:'(HVZ; has α-H)',
        productName:'α-bromo carboxylic acid', productLong:'Bromine installed alpha to the COOH.',
        distractors:[_D.rxvic, _D.acid, _D.ester],
        mechanism:'α-Substitution', explain:'PBr₃ converts COOH → COBr (the acid bromide enol is more accessible). Enol attacks Br₂; hydrolysis returns the acid.' },
      { id:'c08', rxnId:145, reagent:'NaOH (aq), heat', conditions:'(triglyceride)',
        productName:'Glycerol + 3 RCOO⁻ (soap)', productLong:'Three ester linkages saponified at once.',
        distractors:[_D.acid, _D.ald, _D.amide],
        mechanism:'Nucleophilic Acyl Substitution (base)', explain:'OH⁻ attacks each carbonyl; tetrahedral intermediate collapses to release glycerol-O⁻; protonate. Irreversible because RCOO⁻ is unreactive.' },
    ],
  },

  /* ═══════════ 9. ACID CHLORIDE ═══════════ */
  acid_chloride: {
    id: 'acid_chloride',
    label: 'Acid chloride',
    subtitle: 'R-COCl',
    trunkMolecule: null,
    blurb: 'Most reactive acyl derivative. Reacts with practically any O- or N-nucleophile, often without catalyst.',
    branches: [
      { id:'cl01', rxnId:85, reagent:'H₂O', conditions:'',
        productName:_D.acid+' + HCl', productLong:'Hydrolysis — rapid, no catalyst needed.',
        distractors:[_D.ester, _D.amide, _D.ald],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Water adds to the carbonyl; tetrahedral intermediate collapses by expelling Cl⁻; proton transfer.' },
      { id:'cl02', rxnId:86, reagent:'R\u2019OH', conditions:'pyridine or Et₃N',
        productName:_D.ester+' + HCl', productLong:'Cleaner ester synthesis than Fischer — no equilibrium.',
        distractors:[_D.amide, _D.ether, _D.acid],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Alcohol O attacks carbonyl; tetrahedral intermediate; Cl⁻ leaves. Pyridine mops up HCl.' },
      { id:'cl03', rxnId:87, reagent:'R\u2019NH₂ (1° or 2° amine)', conditions:'2 equiv (or amine + base)',
        productName:_D.amide+' + amine·HCl', productLong:'Cleanest amide synthesis.',
        distractors:[_D.amine2, _D.ester, _D.imine],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Amine adds to C=O; tetrahedral intermediate; Cl⁻ leaves; second equiv amine deprotonates. Net: amide + ammonium chloride.' },
    ],
  },

  /* ═══════════ 10. ANHYDRIDE ═══════════ */
  anhydride: {
    id: 'anhydride',
    label: 'Anhydride',
    subtitle: '(RC=O)₂O',
    trunkMolecule: null,
    blurb: 'Second-most-reactive acyl derivative. Behaves like a milder acid chloride.',
    branches: [
      { id:'an01', rxnId:88, reagent:'H₂O', conditions:'',
        productName:'2 RCOOH', productLong:'Both halves of the anhydride hydrolyze to acid.',
        distractors:[_D.ester, _D.amide, _D.ald],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Water attacks one carbonyl; tetrahedral intermediate kicks out RCO-O⁻ (a carboxylate) as the leaving group.' },
      { id:'an02', rxnId:89, reagent:'R\u2019OH', conditions:'pyridine or H⁺',
        productName:_D.ester+' + RCOOH', productLong:'Alcohol acylates one half; the other half becomes acid.',
        distractors:['2 esters', _D.acetal, _D.amide],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Alcohol attacks one carbonyl, carboxylate leaves. Acetic anhydride + ROH → acetate ester + acetic acid.' },
      { id:'an03', rxnId:90, reagent:'R\u2019NH₂', conditions:'',
        productName:_D.amide+' + RCOOH', productLong:'Amine acylates one half; the other half becomes acid.',
        distractors:['2 amides', _D.amine2, _D.ester],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Same pattern as alcoholysis: amine adds, carboxylate leaves.' },
    ],
  },

  /* ═══════════ 11. ESTER ═══════════ */
  ester: {
    id: 'ester',
    label: 'Ester',
    subtitle: 'R-CO-OR\u2019',
    trunkMolecule: 'ethyl_acetate',
    blurb: 'Middle of the acyl reactivity scale. Hydrolysis is everyday; reduction and condensations are the specialty moves.',
    branches: [
      { id:'e01', rxnId:91, reagent:'NaOH (aq), heat', conditions:'(saponification)',
        productName:'Carboxylate + alcohol', productLong:'Irreversible — carboxylate is unreactive.',
        distractors:[_D.acid, _D.amide, _D.ald],
        mechanism:'Nucleophilic Acyl Substitution (base)', explain:'OH⁻ adds to C=O; tetrahedral intermediate kicks out -OR\u2019; proton transfer to give carboxylate and alcohol.' },
      { id:'e02', rxnId:92, reagent:'H₃O⁺, heat', conditions:'',
        productName:_D.acid+' + R\u2019OH', productLong:'Reverse Fischer — equilibrium with starting material.',
        distractors:[_D.amide, _D.ether, _D.ald],
        mechanism:'Acid-Catalyzed PADPED', explain:'Protonate C=O; water adds; tetrahedral intermediate; lose alcohol; deprotonate. Drive forward with excess water.' },
      { id:'e03', rxnId:93, reagent:'R\u2019\u2019OH, H⁺ (or base)', conditions:'(transesterification)',
        productName:'New ester + R\u2019OH', productLong:'Swap one OR group for another.',
        distractors:[_D.acid, _D.acetal, _D.ether],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Alcohol exchange via the same tetrahedral intermediate. Drive with excess new alcohol.' },
      { id:'e04', rxnId:94, reagent:'1) LiAlH₄', conditions:'2) H₂O',
        productName:'2 primary alcohols', productLong:'Cleaves the C-O of the ester; both halves end up as alcohols.',
        distractors:[_D.ald, _D.acid, _D.amine1],
        mechanism:'Hydride Reduction', explain:'First hydride collapses the ester to an aldehyde + alkoxide; second hydride reduces the aldehyde to a 1° alcohol.' },
      { id:'e05', rxnId:95, reagent:'DIBAL-H (1 equiv), –78 °C', conditions:'',
        productName:_D.ald, productLong:'Stops at the aldehyde — the rare reagent that does this.',
        distractors:[_D.alc1, _D.acid, _D.amine1],
        mechanism:'Hydride Addition', explain:'One hydride forms a tetrahedral intermediate that survives at –78 °C; aqueous workup releases the aldehyde.' },
      { id:'e06', rxnId:107, reagent:'NaOEt; then H₃O⁺', conditions:'(2 esters, has α-H)',
        productName:'β-ketoester', productLong:'New C-C bond between α-C of one ester and the carbonyl C of another.',
        distractors:[_D.acid, 'β-diketone', _D.amide],
        mechanism:'Claisen (enolate Nu acyl sub)', explain:'NaOEt forms ester enolate; enolate attacks second ester at C=O; tetrahedral intermediate kicks out -OR\u2019. Final deprotonation of acidic β-keto H drives the equilibrium.' },
      { id:'e07', rxnId:108, reagent:'NaOEt; then H₃O⁺', conditions:'(diester, intramolecular)',
        productName:'Cyclic β-ketoester', productLong:'Intramolecular Claisen condensation — makes a ring.',
        distractors:[_D.lactone, _D.lactam, _D.acid],
        mechanism:'Dieckmann (intramolecular Claisen)', explain:'Same mechanism as Claisen, just within one molecule — favored for 5- and 6-membered rings.' },
      { id:'e08', rxnId:113, reagent:'1) NaOEt 2) R-X', conditions:'3) NaOH/H₂O 4) heat',
        productName:'Substituted acetic acid', productLong:'Use diethyl malonate as a glycine-style synthon for R-CH₂-COOH.',
        distractors:[_D.ester, 'Acrylic acid', _D.amine1],
        mechanism:'Enolate Alkylation + Hydrolysis + Decarboxylation', explain:'Deprotonate the doubly-activated CH₂; alkylate; saponify both esters; decarboxylate the β-keto-style diacid.' },
      { id:'e09', rxnId:114, reagent:'1) NaOEt 2) R-X', conditions:'3) NaOH/H₂O 4) heat',
        productName:'Substituted methyl ketone', productLong:'Same trick as malonic ester, but starting from acetoacetate → ketone product.',
        distractors:[_D.acid, _D.ester, _D.ether],
        mechanism:'Enolate Alkylation + Hydrolysis + Decarboxylation', explain:'Same logic as malonic ester synthesis but the keto group stays, so we get a methyl ketone after losing CO₂.' },
      { id:'e10', rxnId:152, reagent:'NaOH(aq) or LiAlH₄', conditions:'(lactone substrate)',
        productName:'Hydroxy acid (NaOH) or diol (LiAlH₄)', productLong:'Same ester chemistry, but reveals a hydroxy acid or diol because the OR was part of the chain.',
        distractors:[_D.amide, _D.acid, _D.ether],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Ring opens at the C=O — either by OH⁻ (gives the hydroxy carboxylate) or by hydride (gives a diol after two reductions).' },
    ],
  },

  /* ═══════════ 12. AMIDE ═══════════ */
  amide: {
    id: 'amide',
    label: 'Amide',
    subtitle: 'R-CO-NR\u2019₂',
    trunkMolecule: null,
    blurb: 'Least reactive acyl derivative (the N lone pair stabilizes the carbonyl by resonance). Needs harsh conditions or specialty reagents.',
    branches: [
      { id:'am01', rxnId:96, reagent:'H₃O⁺ (conc.)', conditions:'heat',
        productName:_D.acid+' + R₂NH₂⁺', productLong:'Harsh acid hydrolysis cleaves the amide.',
        distractors:[_D.ester, _D.amine1, _D.imine],
        mechanism:'Nucleophilic Acyl Substitution (acid)', explain:'Protonate C=O; water adds; lose amine (now ammonium); deprotonate. Slow because the amide is least reactive.' },
      { id:'am02', rxnId:97, reagent:'NaOH (conc.)', conditions:'heat',
        productName:'RCOO⁻ + R₂NH', productLong:'Base hydrolysis — irreversible.',
        distractors:[_D.ester, _D.imine, _D.amine2],
        mechanism:'Nucleophilic Acyl Substitution (base)', explain:'OH⁻ adds; tetrahedral intermediate ejects R₂N⁻ (it grabs an H instantly to give the amine).' },
      { id:'am03', rxnId:98, reagent:'1) LiAlH₄', conditions:'2) H₂O',
        productName:_D.amine1, productLong:'Loses one O, no carbon change. 1° amide → 1° amine, 2° amide → 2° amine, 3° amide → 3° amine.',
        distractors:[_D.alc1, _D.imine, _D.ald],
        mechanism:'Hydride Reduction', explain:'LiAlH₄ converts C=O to CH₂ without breaking C-N. Unique among acyl reductions — most LAH reductions cleave C-N.' },
      { id:'am04', rxnId:118, reagent:'Br₂, NaOH', conditions:'(1° amide)',
        productName:'1° amine (1 C shorter) + CO₂', productLong:'Hofmann rearrangement: NH₂ migrates from C to N.',
        distractors:[_D.amine2, _D.acid, _D.nitrile],
        mechanism:'Rearrangement (via isocyanate)', explain:'N is halogenated; deprotonation; R group migrates from C to N as Br⁻ leaves → isocyanate; H₂O adds → carbamic acid → R-NH₂ + CO₂.' },
      { id:'am05', rxnId:119, reagent:'R-CO-N₃ → heat', conditions:'(Curtius; from R-COCl + NaN₃)',
        productName:'Isocyanate → amine (H₂O)', productLong:'Same R-from-C-to-N idea as Hofmann, run on an acyl azide.',
        distractors:[_D.amide, _D.nitrile, _D.ald],
        mechanism:'Rearrangement (1,2 shift)', explain:'Heat ejects N₂; concerted R migration gives an isocyanate; water adds to give the carbamic acid, which loses CO₂ to give the amine.' },
      { id:'am06', rxnId:153, reagent:'H₃O⁺ or NaOH, heat', conditions:'(lactam substrate)',
        productName:'Amino acid (or amino carboxylate)', productLong:'Ring opens to reveal both functional groups.',
        distractors:[_D.amide, _D.amine1, _D.ester],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Same amide hydrolysis chemistry, but in a cyclic substrate so the chain stays intact.' },
    ],
  },

  /* ═══════════ 13. NITRILE ═══════════ */
  nitrile: {
    id: 'nitrile',
    label: 'Nitrile',
    subtitle: 'R-C≡N',
    trunkMolecule: null,
    blurb: 'Triple bond to nitrogen. Behaves like a stabilized carbonyl — both C and N can react.',
    branches: [
      { id:'n01', rxnId:99, reagent:'H₃O⁺ (or NaOH), heat', conditions:'',
        productName:_D.acid+' (passes through amide)', productLong:'Two cycles of nucleophilic addition: nitrile → amide → acid.',
        distractors:[_D.amine1, _D.amide+' (only)', _D.ald],
        mechanism:'Addition-Elimination', explain:'Water adds to C≡N → imino acid → tautomerizes to amide → hydrolyzes to acid. All three steps under the same acidic / basic conditions.' },
      { id:'n02', rxnId:100, reagent:'1) LiAlH₄', conditions:'2) H₂O',
        productName:_D.amine1, productLong:'Both C-H bonds added across C≡N; new primary amine.',
        distractors:[_D.amine2, _D.amide, _D.imine],
        mechanism:'Hydride Reduction', explain:'First hydride gives an imine anion; second hydride gives a metallated amine; aqueous workup releases R-CH₂-NH₂.' },
    ],
  },

  /* ═══════════ 14. AMINE ═══════════ */
  amine: {
    id: 'amine',
    label: 'Amine',
    subtitle: 'R-NH₂',
    trunkMolecule: null,
    blurb: 'Soft / basic N lone pair. Acts as nucleophile, base, and in quaternary salts as a leaving group (after methylation).',
    branches: [
      { id:'am01', rxnId:122, reagent:'R-X (1° halide)', conditions:'',
        productName:'Higher-order amine / quat salt', productLong:'1°→2°→3°→quaternary ammonium. Hard to control.',
        distractors:[_D.amide, _D.imine, _D.alc1],
        mechanism:'SN2', explain:'Amine SN2s on R-X; each successive amine is more nucleophilic, so over-alkylation is the rule. Use Gabriel synthesis or reductive amination instead.' },
      { id:'am02', rxnId:123, reagent:'RCOCl or anhydride', conditions:'pyridine',
        productName:_D.amide, productLong:'N-acylation gives an amide.',
        distractors:[_D.imine, _D.amine2, _D.ester],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Same as in the acid chloride tree: amine adds to C=O; LG (Cl⁻ or carboxylate) leaves.' },
      { id:'am03', rxnId:120, reagent:'Heat (Ag₂O converts I to OH)', conditions:'(R₄N⁺ OH⁻)',
        productName:'Hofmann alkene (less subst.)', productLong:'Anti-Zaitsev: bulky N⁺R₃ leaving group pushes elimination to the less hindered alkene.',
        distractors:['Zaitsev alkene', _D.alkene, _D.amine3],
        mechanism:'E2', explain:'Trimethylamine is a bulky leaving group; the only accessible β-H is on the least hindered carbon → less substituted alkene.' },
      { id:'am04', rxnId:121, reagent:'Heat (~100 °C)', conditions:'(R₃N⁺-O⁻)',
        productName:'Less substituted alkene + R₂NOH', productLong:'Same Hofmann-style selectivity but syn periplanar.',
        distractors:['Zaitsev alkene', _D.amide, _D.imine],
        mechanism:'Syn Elimination', explain:'5-membered cyclic TS: O of N-oxide grabs a β-H on the same face as N leaves. Net syn-periplanar elimination.' },
      { id:'am05', rxnId:117, reagent:'1) phthalimide/KOH 2) R-X', conditions:'3) N₂H₄ or H₃O⁺',
        productName:_D.amine1+' (mono-alkylated)', productLong:'Gabriel synthesis avoids over-alkylation.',
        distractors:[_D.amine2, _D.amide, _D.amine3],
        mechanism:'SN2 + hydrolysis', explain:'Phthalimide N⁻ does SN2 on R-X (one alkylation only — the N now has no acidic H). Hydrazine then peels off the phthaloyl group to release the primary amine.' },
    ],
  },

  /* ═══════════ 15. EPOXIDE ═══════════ */
  epoxide: {
    id: 'epoxide',
    label: 'Epoxide',
    subtitle: '3-mem C-O ring',
    trunkMolecule: null,
    blurb: 'Strained 3-membered ring. Opens with nucleophiles; selectivity for which C is attacked depends on whether the conditions are acidic or basic.',
    branches: [
      { id:'ep01', rxnId:64, reagent:'H₃O⁺ (+ Nu)', conditions:'',
        productName:'Trans diol (Nu at more sub. C)', productLong:'Acid-catalyzed: Nu opens the ring at the MORE substituted C.',
        distractors:['Cis diol', _D.epoxide, _D.alc1],
        mechanism:'SN1-like', explain:'Acid protonates O; partial cation character builds on the more substituted C; Nu attacks there. Stereochemistry remains anti.' },
      { id:'ep02', rxnId:65, reagent:'NaOH (or strong Nu⁻)', conditions:'',
        productName:'Trans product (Nu at less sub. C)', productLong:'Basic conditions: Nu opens ring at the LESS hindered C (SN2 selectivity).',
        distractors:['Cis product', _D.diol_gem, _D.ket],
        mechanism:'SN2', explain:'Without acid, the Nu just SN2s on the less hindered C; trans relative geometry preserved.' },
    ],
  },

  /* ═══════════ 16. ETHER ═══════════ */
  ether: {
    id: 'ether',
    label: 'Ether',
    subtitle: 'R-O-R',
    trunkMolecule: null,
    blurb: 'Boring on a good day. Inert to most reagents; the one major reaction is cleavage with HX.',
    branches: [
      { id:'et01', rxnId:63, reagent:'HI or HBr (excess), heat', conditions:'',
        productName:'2 alkyl halides (or alcohol + R-X)', productLong:'C-O bonds break; halogens cap both ends.',
        distractors:[_D.diol_vic, _D.alc1, _D.epoxide],
        mechanism:'SN2 (1°) or SN1 (3°)', explain:'Protonate O to make it a leaving group; X⁻ then SN2s a primary alkyl off (or SN1 from a tertiary). Repeat with the alcohol.' },
    ],
  },

  /* ═══════════ 17. CONJUGATED DIENE ═══════════ */
  diene: {
    id: 'diene',
    label: 'Conjugated diene',
    subtitle: 'C=C-C=C',
    trunkMolecule: null,
    blurb: 'Two conjugated π bonds. The signature reaction is the Diels–Alder; thermal electrocyclics also live here.',
    branches: [
      { id:'di01', rxnId:124, reagent:'Dienophile (alkene/alkyne EWG)', conditions:'heat',
        productName:'Cyclohexene (or cyclohexadiene)', productLong:'New 6-membered ring; endo product favored kinetically.',
        distractors:[_D.cyclopropane, _D.diol_vic, _D.alkane],
        mechanism:'[4+2] Cycloaddition', explain:'Six π electrons reorganize in one concerted, suprafacial step. Allowed thermally by Woodward-Hoffmann.' },
      { id:'di02', rxnId:126, reagent:'Heat', conditions:'(butadiene)',
        productName:'Cyclobutene (conrotatory)', productLong:'4 electrons + thermal → conrotatory ring closure.',
        distractors:['Cyclobutene (disrotatory)', 'Cyclohexadiene', _D.cyclopropane],
        mechanism:'Electrocyclic', explain:'4 π electrons thermal = conrotatory. The two end groups rotate in the same direction as the σ bond forms.' },
      { id:'di03', rxnId:127, reagent:'hν', conditions:'(butadiene)',
        productName:'Cyclobutene (disrotatory)', productLong:'Photochemical mode reverses the rotation rule.',
        distractors:['Cyclobutene (conrotatory)', 'Cyclohexadiene', _D.diol_vic],
        mechanism:'Electrocyclic (photochemical)', explain:'Photoexcitation flips the parity of the HOMO; thermal-allowed conrotatory becomes photochemical-allowed disrotatory.' },
      { id:'di04', rxnId:128, reagent:'Heat', conditions:'(hexatriene)',
        productName:'Cyclohexadiene (disrotatory)', productLong:'6 electrons + thermal → disrotatory ring closure.',
        distractors:['Cyclohexadiene (conrotatory)', _D.cyclopropane, _D.diene],
        mechanism:'Electrocyclic', explain:'6 π electrons thermal = disrotatory. Opposite to the 4-electron case.' },
      { id:'di05', rxnId:131, reagent:'Heat', conditions:'(1,3-diene with allylic C-H, cis)',
        productName:'Isomeric 1,3-diene', productLong:'H migrates across 5 atoms suprafacially.',
        distractors:['Cyclopentadiene', _D.alkane, _D.diol_vic],
        mechanism:'[1,5]-H Sigmatropic', explain:'H migrates over 5 atoms (1→5) keeping the same face. Common in cyclopentadiene-type dienes.' },
    ],
  },

  /* ═══════════ 18. α,β-UNSATURATED CARBONYL ═══════════ */
  enone: {
    id: 'enone',
    label: 'α,β-unsaturated carbonyl',
    subtitle: 'C=C-C=O',
    trunkMolecule: null,
    blurb: 'Conjugated electrophile. Soft nucleophiles add at β-C (1,4-addition); hard ones add at the carbonyl (1,2-addition).',
    branches: [
      { id:'en01', rxnId:109, reagent:'Soft Nu⁻ (enolate, amine, RS⁻)', conditions:'base or acid (cat.)',
        productName:'1,4-addition product', productLong:'Nu adds at the β-carbon; carbonyl reforms.',
        distractors:['1,2-addition product (at C=O)', _D.epoxide, _D.alc1],
        mechanism:'Conjugate Addition (Michael)', explain:'Soft, stabilized nucleophiles prefer the conjugated π position. The enolate that forms then protonates to restore the carbonyl.' },
      { id:'en02', rxnId:110, reagent:'Methyl vinyl ketone + ketone (Robinson)', conditions:'NaOEt or NaOH',
        productName:'Cyclohexenone', productLong:'Michael, then intramolecular aldol condensation.',
        distractors:[_D.diol_vic, _D.lactam, _D.lactone],
        mechanism:'Michael + Aldol Cond.', explain:'Enolate of the ketone does conjugate addition to MVK; the resulting 1,5-diketone undergoes intramolecular aldol condensation to give the 6-membered enone.' },
      { id:'en03', rxnId:158, reagent:'Base', conditions:'(β-halo carbonyl substrate)',
        productName:'α,β-unsaturated carbonyl', productLong:'Loss of HX with a stabilized carbanion intermediate.',
        distractors:[_D.alkene, _D.ester, _D.amide],
        mechanism:'E1cb', explain:'Acidic α-H removed first → stabilized carbanion (enolate); then β-LG leaves to form the new alkene. Common in β-halo / β-tosyl carbonyls.' },
    ],
  },

  /* ═══════════ 19. SIGMATROPIC SUBSTRATES (1,5-DIENE & ALLYL VINYL ETHER) ═══════════ */
  sigmatropic: {
    id: 'sigmatropic',
    label: 'Sigmatropic substrates',
    subtitle: '1,5-diene / allyl vinyl ether',
    trunkMolecule: null,
    blurb: 'Both rearrange via a 6-membered chair-like TS. No catalyst; just heat.',
    branches: [
      { id:'si01', rxnId:129, reagent:'Heat', conditions:'(1,5-diene)',
        productName:'Isomeric 1,5-diene', productLong:'[3,3] sigmatropic — the two ends swap places.',
        distractors:[_D.cyclopropane, _D.diene, _D.alkane],
        mechanism:'Cope Rearrangement', explain:'6-membered chair TS allows a σ bond to migrate to the other end. Symmetric — equilibrates between two 1,5-dienes.' },
      { id:'si02', rxnId:130, reagent:'Heat', conditions:'(allyl vinyl ether / allyl aryl ether)',
        productName:'γ,δ-unsaturated carbonyl', productLong:'[3,3] with an oxygen in the chain.',
        distractors:[_D.ester, _D.acetal, _D.ket],
        mechanism:'Claisen Rearrangement', explain:'Same chair TS as Cope, but with an O in the ring. Gives a γ,δ-unsaturated carbonyl (or ortho-allyl phenol from aryl version).' },
    ],
  },

  /* ═══════════ 20. CARBOHYDRATE ═══════════ */
  sugar: {
    id: 'sugar',
    label: 'Carbohydrate',
    subtitle: 'Reducing sugar',
    trunkMolecule: null,
    blurb: 'Polyhydroxy aldehyde / ketone. Anomeric carbon is the hub of the chemistry.',
    branches: [
      { id:'sg01', rxnId:139, reagent:'Tollens / Fehling / Benedict', conditions:'',
        productName:'Aldonate + Ag⁰ or Cu₂O', productLong:'Tests for reducing sugars; ketoses tautomerize to aldoses.',
        distractors:[_D.alc1, _D.ester, _D.amide],
        mechanism:'Oxidation', explain:'Carbonyl C oxidized to acid; metal reduced (Ag⁺→Ag⁰, Cu²⁺→Cu₂O). Brick-red Cu₂O is the positive Benedict\u2019s/Fehling\u2019s result.' },
      { id:'sg02', rxnId:140, reagent:'NaBH₄ (or H₂/Ni)', conditions:'',
        productName:'Alditol (sugar alcohol)', productLong:'Carbonyl reduced — all carbons now bear OH.',
        distractors:['Aldonate', _D.amine1, _D.acid],
        mechanism:'Hydride Reduction', explain:'Just like reducing any aldehyde/ketone; result is a polyol.' },
      { id:'sg03', rxnId:141, reagent:'ROH, H⁺ (Fischer glycosylation)', conditions:'',
        productName:'Glycoside (anomeric acetal)', productLong:'Acetal at the anomeric C; α/β mixture (thermo control).',
        distractors:[_D.ester, _D.ether, _D.ald],
        mechanism:'Acetal Formation', explain:'Standard acetal mechanism at the anomeric C. The product is locked — no longer a reducing sugar.' },
      { id:'sg04', rxnId:142, reagent:'Excess PhNHNH₂, heat', conditions:'',
        productName:'Osazone (bis-hydrazone)', productLong:'Hydrazone at both C1 and C2; classic sugar test.',
        distractors:[_D.imine, _D.hydrazone, _D.amide],
        mechanism:'Addition-Elimination (×2)', explain:'Three equivalents of phenylhydrazine: first forms hydrazone at C1; second oxidizes C2 OH to C=O; third hydrazone at C2.' },
    ],
  },

  /* ═══════════ 21. PEPTIDE ═══════════ */
  peptide: {
    id: 'peptide',
    label: 'Peptide / amino acid',
    subtitle: 'H₂N-CHR-COOH',
    trunkMolecule: null,
    blurb: 'Amide formation between amino acids; selective N-terminal degradation for sequencing.',
    branches: [
      { id:'pe01', rxnId:143, reagent:'DCC / EDC / HATU + base', conditions:'(protecting groups in synthesis)',
        productName:'Dipeptide + H₂O', productLong:'New amide bond between C of one residue and N of the next.',
        distractors:[_D.ester, _D.amine1, _D.imine],
        mechanism:'Nucleophilic Acyl Substitution', explain:'Coupling agent activates the carboxylate as an acylium-like species; amine attacks; couple. PG strategy decides which amine and acid actually react.' },
      { id:'pe02', rxnId:144, reagent:'1) PhNCS, pH 8', conditions:'2) HF or TFA',
        productName:'PTH-amino acid + (n-1) peptide', productLong:'Removes one residue from the N-terminus at a time.',
        distractors:[_D.amine1, _D.acid, _D.amide],
        mechanism:'Edman Degradation', explain:'PhNCS attaches to terminal NH₂; acid cleaves the first amide; the released residue cyclizes to a PTH (phenylthiohydantoin) identifiable by chromatography.' },
    ],
  },

  /* ═══════════ 22. THIOL / SULFIDE ═══════════ */
  thiol: {
    id: 'thiol',
    label: 'Thiol / sulfide',
    subtitle: 'R-SH / R-S-R',
    trunkMolecule: null,
    blurb: 'Soft, polarizable S. Acts like a nucleophilic alcohol but tougher.',
    branches: [
      { id:'th01', rxnId:155, reagent:'R-X, base', conditions:'',
        productName:'Thioether (R-S-R\u2019)', productLong:'Like Williamson ether synthesis with S replacing O.',
        distractors:['Disulfide', _D.ether, _D.amine1],
        mechanism:'SN2', explain:'Base deprotonates RSH to RS⁻; the thiolate SN2s on R\u2019X. Excellent nucleophile.' },
      { id:'th02', rxnId:156, reagent:'R-X, heat', conditions:'(R-S-R substrate)',
        productName:'Trialkylsulfonium salt (R₃S⁺)', productLong:'Sulfides alkylate with a third R, making a sulfonium salt.',
        distractors:[_D.ether, 'Disulfide', _D.amine3],
        mechanism:'SN2', explain:'Lone pair on S of a sulfide can still act as a nucleophile against a primary halide. Stable salts.' },
      { id:'th03', rxnId:157, reagent:'I₂ (or O₂, H₂O₂)', conditions:'',
        productName:'Disulfide (R-S-S-R)', productLong:'Oxidative coupling — important in biology (cysteine disulfides).',
        distractors:['Sulfide', 'Sulfoxide', _D.ether],
        mechanism:'Oxidation', explain:'Two thiols join with loss of 2 H. Reversible — DTT/TCEP reduce disulfides back to thiols.' },
      { id:'th04', rxnId:137, reagent:'1,3-dithiane, BuLi; then R-X', conditions:'then HgCl₂/H₂O',
        productName:_D.ald+' (umpolung)', productLong:'1,3-dithiane acts as an acyl anion equivalent — reversed polarity!',
        distractors:[_D.ket, _D.ester, _D.amine1],
        mechanism:'Umpolung (Corey-Seebach)', explain:'BuLi deprotonates the C between the two S; that carbanion SN2s on R-X; hydrolysis of the dithiane unmasks the aldehyde. We just made R-CHO from R-X.' },
    ],
  },

  /* ═══════════ 23. GRIGNARD / ORGANOLITHIUM ═══════════ */
  grignard: {
    id: 'grignard',
    label: 'Grignard / R-Li',
    subtitle: 'R-MgX, R-Li',
    trunkMolecule: null,
    blurb: 'Carbanion equivalents. React with anything more electrophilic than water — pick the electrophile to choose the alcohol class.',
    branches: [
      { id:'gr01', rxnId:31, reagent:'RCHO (aldehyde)', conditions:'then H₃O⁺',
        productName:_D.alc2, productLong:'Adds across the C=O; one R from Grignard, one from aldehyde.',
        distractors:[_D.alc1, _D.alc3, _D.ket],
        mechanism:'Nucleophilic Addition', explain:'R⁻ attacks C=O; alkoxide intermediate; H₃O⁺ protonates. Aldehydes give 2° alcohols.' },
      { id:'gr02', rxnId:32, reagent:'R₂C=O (ketone)', conditions:'then H₃O⁺',
        productName:_D.alc3, productLong:'Ketones give 3° alcohols.',
        distractors:[_D.alc1, _D.alc2, _D.ester],
        mechanism:'Nucleophilic Addition', explain:'Same as above; ketones already have two Rs on the carbonyl carbon, so adding the Grignard gives a 3° alcohol after workup.' },
      { id:'gr03', rxnId:33, reagent:'H₂C=O (formaldehyde)', conditions:'then H₃O⁺',
        productName:_D.alc1, productLong:'Formaldehyde adds one carbon → 1° alcohol.',
        distractors:[_D.alc2, _D.alc3, _D.acid],
        mechanism:'Nucleophilic Addition', explain:'No R groups on the carbonyl C — adding the Grignard gives RCH₂OH.' },
      { id:'gr04', rxnId:34, reagent:'CO₂', conditions:'then H₃O⁺',
        productName:_D.acid, productLong:'Add one carbon as COOH.',
        distractors:[_D.ester, _D.amide, _D.ald],
        mechanism:'Nucleophilic Addition', explain:'R⁻ attacks C=O of CO₂; carboxylate; protonate.' },
      { id:'gr05', rxnId:35, reagent:'Ester (2 equiv RMgX)', conditions:'then H₃O⁺',
        productName:_D.alc3+' (2 R from Grignard)', productLong:'Two adds: tetrahedral intermediate collapses to a ketone (which is more reactive than ester), so Grignard adds again.',
        distractors:[_D.alc2, _D.ald, _D.ket],
        mechanism:'Acyl Sub + Addition', explain:'First Grignard kicks out -OR\u2019 to give a ketone; second Grignard then adds to the ketone. Net: 3° alcohol with two of the new R groups.' },
      { id:'gr06', rxnId:37, reagent:'Aldehyde or ketone', conditions:'(R-Li, dry ether)',
        productName:_D.alc2+' or '+_D.alc3, productLong:'Organolithium is more reactive, less selective.',
        distractors:[_D.alkane, _D.amine1, _D.ether],
        mechanism:'Nucleophilic Addition', explain:'R-Li is a stronger nucleophile / base than RMgX; adds to even hindered ketones. Same products, same logic.' },
    ],
  },

  /* ═══════════ 24. ALKENE PHOTOCHEMICAL [2+2] ═══════════ */
  alkene_hv: {
    id: 'alkene_hv',
    label: 'Two alkenes + hν',
    subtitle: '2 × C=C',
    trunkMolecule: null,
    blurb: 'Photochemistry switches selection rules: thermally-forbidden [2+2] becomes allowed.',
    branches: [
      { id:'ph01', rxnId:125, reagent:'2 alkenes', conditions:'hν',
        productName:'Cyclobutane', productLong:'Two alkenes fused to a 4-membered ring.',
        distractors:['Cyclohexene', _D.diol_vic, _D.cyclopropane],
        mechanism:'[2+2] Cycloaddition (photochemical)', explain:'Photoexcitation gives a singlet diradical-like species; concerted, suprafacial coupling forms two new σ bonds and one ring. Thermally forbidden, photochemically allowed.' },
    ],
  },

  /* ═══════════ 25. CARBOCATION REARRANGEMENT (META) ═══════════ */
  carbocation: {
    id: 'carbocation',
    label: 'Carbocation rearrangement',
    subtitle: 'R⁺',
    trunkMolecule: null,
    blurb: 'Whenever a cation forms (E1, SN1, alcohol dehydration, halide ionization, etc.), watch for 1,2-shifts to give a more stable cation.',
    branches: [
      { id:'cc01', rxnId:159, reagent:'Cation adjacent to higher-sub. C', conditions:'',
        productName:'Rearranged (more stable) cation', productLong:'A nearby H migrates to give a better cation.',
        distractors:['Original cation', _D.alkene, _D.alkane],
        mechanism:'1,2-Hydride Shift', explain:'An adjacent C-H bond migrates with both electrons to the cation, leaving a new cation on the other carbon — usually more substituted, more stable.' },
      { id:'cc02', rxnId:160, reagent:'Cation adjacent to branch', conditions:'',
        productName:'Rearranged (more stable) cation', productLong:'A nearby alkyl group migrates instead of H.',
        distractors:['Original cation', _D.alkene, _D.alkane],
        mechanism:'1,2-Alkyl Shift', explain:'Same trick as hydride shift but the migrating group is an alkyl. Often unavoidable in Friedel-Crafts alkylation of n-propyl/n-butyl halides → over-rearrangement.' },
    ],
  },

};

/* Index reactions by id for fast lookup */
const RXN_INDEX = {};
for (const tree of Object.values(TREES)) {
  for (const b of tree.branches) {
    if (b.rxnId) RXN_INDEX[b.rxnId] = { tree: tree.id, branch: b };
  }
}

Object.assign(window, { TREES, RXN_INDEX });
